# Generated by Django 5.0.7 on 2024-07-29 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeblocks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='codeblock',
            name='id',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False),
        ),
    ]
