# Generated by Django 4.2.7 on 2024-07-31 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeblocks', '0002_submission_instructions_submission_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='title',
            new_name='user_id',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='submission',
            name='user',
        ),
    ]
