# Generated by Django 5.0.7 on 2024-07-30 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeblocks', '0002_alter_codeblock_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='codeblock',
            name='instractions',
            field=models.TextField(default='default'),
            preserve_default=False,
        ),
    ]
