# Generated by Django 4.2.7 on 2024-07-31 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeblocks', '0003_rename_title_submission_user_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_uuid', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
