# Generated by Django 5.0.7 on 2024-07-30 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('codeblocks', '0003_codeblock_instractions'),
    ]

    operations = [
        migrations.RenameField(
            model_name='codeblock',
            old_name='instractions',
            new_name='instructions',
        ),
    ]
