# Generated by Django 5.0.7 on 2024-07-30 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeblocks', '0004_rename_instractions_codeblock_instructions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='codeblock',
            name='solution',
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_code', models.TextField()),
                ('user', models.CharField(max_length=100)),
                ('passed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('code_block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codeblocks.codeblock')),
            ],
        ),
    ]
