# Generated by Django 4.2.7 on 2024-07-31 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codeblocks', '0004_visitor'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='role',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
